// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Generate CUGA settings.yaml and .env from NemoClaw build-arg env vars.
//
// Called at Docker image build time (and re-callable at runtime). Reads
// NEMOCLAW_* env vars and writes:
//   /sandbox/.cuga/settings.yaml   — CUGA configuration (immutable at runtime)
//   /sandbox/.cuga/.env            — runtime API key (mode 0640, sandbox-owned)
//
// Sets what CUGA needs to run inside an OpenShell sandbox:
//   - LLM provider/model (custom OpenAI-compatible endpoint → inference.local)
//   - Server bind address + port (8005, matching agents/cuga/manifest.yaml)
//   - Bearer-token API key for the dashboard (CUGA_API_KEY)
//   - Default mcp_servers.yaml / playbooks dirs (mount points)

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname } from "node:path";

interface CugaBuildSettings {
  model: string;
  providerKey: string;
  baseUrl: string;
  apiKey: string;
  configDir: string;
}

function readSettings(env: NodeJS.ProcessEnv): CugaBuildSettings {
  const model = env.NEMOCLAW_MODEL?.trim();
  const providerKey = env.NEMOCLAW_PROVIDER_KEY?.trim() || "custom";
  const baseUrl = env.NEMOCLAW_INFERENCE_BASE_URL?.trim() || "https://inference.local/v1";
  const apiKey = env.NEMOCLAW_CUGA_API_KEY?.trim() || "";
  if (!model) {
    throw new Error("NEMOCLAW_MODEL is required (e.g. 'openai/gpt-4o-mini')");
  }
  return {
    model,
    providerKey,
    baseUrl,
    apiKey,
    configDir: env.CUGA_HOME?.trim() || "/sandbox/.cuga",
  };
}

function yamlEscape(value: string): string {
  // Quote anything with special YAML meaning. For settings we accept
  // only ASCII model names / URLs, so a simple single-quoted form is safe.
  return `'${value.replace(/'/g, "''")}'`;
}

function renderSettingsYaml(s: CugaBuildSettings): string {
  return [
    "# Generated by NemoClaw at image build time. Do not edit by hand —",
    "# changes will be overwritten on the next `nemocuga upgrade`.",
    "",
    "server:",
    "  host: 0.0.0.0",
    "  port: 8005",
    "  bind_internal: 0.0.0.0:8005   # OpenShell forwards to host",
    "",
    "auth:",
    "  method: bearer_token",
    "  env_var: CUGA_API_KEY",
    "",
    "model:",
    `  default: ${yamlEscape(s.model)}`,
    `  provider: ${yamlEscape(s.providerKey)}`,
    `  base_url: ${yamlEscape(s.baseUrl)}`,
    "  # API key for the upstream provider comes from the routed",
    "  # inference proxy (inference.local), not from this file.",
    "",
    "paths:",
    `  state_dir: ${yamlEscape(s.configDir)}`,
    `  mcp_servers_file: ${yamlEscape(`${s.configDir}/mcp_servers.yaml`)}`,
    `  playbooks_dir: ${yamlEscape(`${s.configDir}/playbooks`)}`,
    `  knowledge_dir: ${yamlEscape(`${s.configDir}/knowledge`)}`,
    `  sessions_dir: ${yamlEscape(`${s.configDir}/sessions`)}`,
    `  logs_dir: ${yamlEscape(`${s.configDir}/logs`)}`,
    "",
    "reasoning:",
    "  mode: balanced              # fast | balanced | accurate",
    "  max_planner_iterations: 4",
    "",
    "policies:",
    "  intent_guards: true",
    "  tool_approval:",
    "    require_for: [web_post, mutating_api]",
    "",
    "logging:",
    "  level: info",
    "  format: json",
    "",
  ].join("\n");
}

function renderEnvFile(s: CugaBuildSettings): string {
  // CUGA_API_KEY is rotated by `nemocuga credentials set api-key`.
  // The build-time value is a seed; an empty seed means "generate at first start".
  return [
    "# Generated by NemoClaw. Sandbox-readable, not committed to image history.",
    `CUGA_API_KEY=${s.apiKey}`,
    "",
  ].join("\n");
}

function ensureDir(path: string): void {
  if (!existsSync(path)) mkdirSync(path, { recursive: true, mode: 0o770 });
}

function main(): void {
  const settings = readSettings(process.env);
  const configPath = `${settings.configDir}/settings.yaml`;
  const envPath = `${settings.configDir}/.env`;
  ensureDir(dirname(configPath));
  writeFileSync(configPath, renderSettingsYaml(settings), { mode: 0o640 });
  writeFileSync(envPath, renderEnvFile(settings), { mode: 0o640 });
  console.log(`[config] Wrote ${configPath} (model=${settings.model}, provider=${settings.providerKey})`);
  console.log(`[config] Wrote ${envPath}`);
}

main();
